---
- hosts: all
  become: yes
  
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped
      when: ansible_os_family == "Debian"
   
    - name: ensure nginx is not installed in Ubuntu
      apt: name=nginx state=absent
      when: ansible_os_family == "Debian"
    
    - name: ensure nginx is not installed in RedHat
      yum: name=nginx state=absent
      when: ansible_os_family == "RedHat"


    - name: remove dir contents from servers in Ubuntu
      file: path='/var/www/html' state=absent
      when: ansible_os_family == "Debian"

    - name: remove dir contents from servers in RedHat
      file: path='/usr/share/nginx/html/' state=absent
      when: ansible_os_family == "RedHat"     







